# Generated by Django 3.1.2 on 2020-10-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0002_auto_20201020_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='randomizer',
            name='word1',
        ),
        migrations.RemoveField(
            model_name='randomizer',
            name='word2',
        ),
        migrations.RemoveField(
            model_name='randomizer',
            name='word3',
        ),
        migrations.RemoveField(
            model_name='randomizer',
            name='word4',
        ),
        migrations.RemoveField(
            model_name='randomizer',
            name='word5',
        ),
        migrations.RemoveField(
            model_name='randomizer',
            name='word6',
        ),
        migrations.RemoveField(
            model_name='randomizer',
            name='word7',
        ),
        migrations.RemoveField(
            model_name='randomizer',
            name='word81',
        ),
        migrations.RemoveField(
            model_name='randomizer',
            name='word82',
        ),
    ]
