# Generated by Django 3.1.2 on 2020-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0005_item8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item1',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='item2',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='item3',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='item4',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='item5',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='item6',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='item7',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='item8',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='item81',
            name='item',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='item82',
            name='item',
            field=models.CharField(max_length=60),
        ),
    ]
