# Generated by Django 3.1.1 on 2020-10-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedbacksys',
        ),
    ]
