# Generated by Django 3.1.2 on 2020-10-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
