# Generated by Django 3.1.2 on 2020-10-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20201021_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
