# Generated by Django 3.1.1 on 2020-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=120)),
                ('nickname', models.TextField()),
                ('password', models.DateTimeField()),
            ],
        ),
    ]
